### ISSUE TITLE
Decoding COSE headers

### ISSUE THREAD

**Issue by simonh1000** [elm-toulouse/cbor#3]
I've returned to this work and am now looking at the headers of the EU Green Pass.  In the test data I am using, these look like

`{ 1 => -7, 4 => <Buffer 38 3a 9a 1b c9 a7 6e ba> }`

But the keys and values can vary in practise.  With knowledge of the _exact_ structure I can decode this, but any more general attempt I make to decode structures like this fail. Headers can vary so I need a more general solution

You can try this at https://ellie-app.com/f5gXFdkDHdDa1 and note there that I have added some other decoding attempts that I have tried

**Comment by KtorZ** [comment]
The most flexible solution would be to combine the new primitives from 1.1.0, namely [`keyValueMap`](https://package.elm-lang.org/packages/elm-toulouse/cbor/latest/Cbor-Decode#keyValueMap) and [`any`](https://package.elm-lang.org/packages/elm-toulouse/cbor/latest/Cbor-Decode#any) although, I don't think _any_ is a viable solution for anything to use in production code: it it _too generic_ and introduces branches to handle that are likely non necessary.

Ideally, we would like to be able to have alternative decoders, but behind the scene this library heavily relies on the elm/bytes library which provides no way to write alternative decoders or to look ahead. Yet, since CBOR is self describing and, each item has a major type, it may be possible to implement some form of alternative decoder. That would allow selecting different keys or values types without going for the full generic version that is any.

Arguably, whoever chose the CBOR representation you're decoding didn't thought carefully about the consequences on statically typed languages...

**Comment by simonh1000** [comment]
this reminds me that you did not publish 1.1.0 yet

**Comment by simonh1000** [comment]
Should we raise an issue on elm/bytes?

**Comment by KtorZ** [comment]
> this reminds me that you did not publish 1.1.0 yet

I am pretty sure I did 😶. What do you mean?

**Comment by simonh1000** [comment]
> > this reminds me that you did not publish 1.1.0 yet
> 
> I am pretty sure I did 😶. What do you mean?

Something is not quite right - see https://package.elm-lang.org/packages/elm-toulouse/cbor/
there are traces of 1.1.0 on the site (and in google) but 1.1.0 is not properly marked as 'latest'

**Comment by KtorZ** [comment]
This should be addressed in [v2.0.0 and the new API for records and tuples](https://package.elm-lang.org/packages/elm-toulouse/cbor/2.0.0/Cbor-Decode#records-tuples)
